name: Build CI

on:
  push:
    branches: [ main ]

  label:
    name: MacOS build
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload TheAirBlow.Thor.GUI binary
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "TheAirBlow.Thor.GUI-macos"
        path: "TheAirBlow.Thor.GUI/bin/"
